---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
{{- if .metadata.annotations }}
  annotations:
{{- range $key, $value := .metadata.annotations }}
    {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
