---
apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: {{ .metadata.name }}
  namespace: "openshift-local-storage"
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  logLevel: Normal
  managementState: Managed
  {{- if .spec.nodeSelector }}
  nodeSelector:
    {{- .spec.nodeSelector | toYaml | nindent 4 }}
  {{- end }}
  storageClassDevices:
    {{- range .spec.storageClassDevices }}
    - storageClassName: {{ .storageClassName }}
      forceWipeDevicesAndDestroyAllData: true
      {{- if or (eq .volumeMode "Block") (eq .volumeMode "Filesystem") }}
      volumeMode: {{ .volumeMode }}
      {{- else }}
      volumeMode: must be 'Block' or 'Filesystem'
      {{- end }}
      devicePaths:
        {{- .devicePaths | toYaml | nindent 8 }}
    {{- end }}
