---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-ssh-known-hosts-cm
  namespace: openshift-gitops
data:
{{- if .data }}
  ssh_known_hosts: |
{{ index .data "ssh_known_hosts" | trimSuffix "\n" | indent 4 }}
{{- end }}
