apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
{{- if .spec }}
spec:
  {{- if .spec.nodeSelector }}
  nodeSelector:
    {{- .spec.nodeSelector | toYaml | nindent 4 }}
  {{- end }}
  #nodeSelector:
  #  node-role.kubernetes.io/worker: ""
  {{- if .spec.loadBalancerClass }}
  loadBalancerClass: {{- .spec.loadBalancerClass | toYaml | nindent 4 }}
  {{- end }}
  # loadBalancerClass: "metallb-class1"
{{- end }}
