# Optional
# count: 1
apiVersion: nodetopology.openshift.io/v1
kind: NUMAResourcesOperator
metadata:
  name: numaresourcesoperator
spec:
{{- if .spec.logLevel }}
  logLevel: {{ .spec.logLevel }}
{{- end }}
  nodeGroups:
  {{- if .spec.nodeGroups }}
    {{- range .spec.nodeGroups }}
    - config:
        # Periodic is the default setting
        infoRefreshMode: Periodic
      {{- if .machineConfigPoolSelector }}
      machineConfigPoolSelector:
        {{- .machineConfigPoolSelector | toYaml | nindent 8 }}
      {{- end }}
#      matchLabels:
#        # This label must match the pool(s) you want to run NUMA-aligned workloads
#        pools.operator.machineconfiguration.openshift.io/worker: ""
    {{- end }}
  {{- else }}
    []
  {{- end }}
