---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-45"
  labels:
    openshift.io/cluster-monitoring: "true"
  name: open-cluster-management-observability
